### ISSUE TITLE
metaslider

### ISSUE THREAD

**Issue by harry-huddle** [outlandishideas/wpackagist#102]
This is active on Wordpress.org but doesn't give a version and says it inactive on wpackagist.

**Comment by louim** [comment]
I think you are looking for https://wordpress.org/plugins/ml-slider/  which would be here: http://wpackagist.org/search?q=ml-slider&type=any&search= 

I know currently search is a little confusing because you need to search for the plugin unique identifier aka "slug". There is a pull request pending that try to fix this: #100.
