### ISSUE TITLE
"url" switches between http and https in lockfile

### ISSUE THREAD

**Issue by khromov** [outlandishideas/wpackagist#116]
Resurrecting #63 

We still have problems that WPackagist keeps switching between http and https for the "url" field.  Eearlier we had this problem for the "homepage" field but now it is the "url" field.

When I look in `/home/.composer/cache/repo/http---wpackagist.org` I can see that the JSON blobs do in fact contain http in my case and https for my co-worker.

Same version of Composer on both machines. Tried deleting .cache folder but still same difference. Reaching the limits of my sanity here. :8ball:  Any help appreciated!

**Comment by khromov** [comment]
**Screenshot**
![Uploading composer.lock+%28%2FUsers%2Fjohcar2%2FDevelopment%2Fwordpress-ab%29+2015-10-05+13-45-24.png…]()

**Comment by aaemnnosttv** [comment]
I've had this problem before but in my experience it is just a matter of how Composer works, not wpackagist.

Composer keeps a `vendor/composer/installed.json` file, similar to `composer.lock`. Unlike the lock file which is rebuilt on every `composer update`, this file persists but affects how the lock file is generated. All you should need to do is update the urls as necessary within the `installed.json` file, and then everything should be using the proper protocol going forward when you run `composer update`. You shouldn't need to update it again.

**Comment by khromov** [comment]
@aaemnnosttv So you are saying that deleting the `vendor` folder and running running `composer install` should solve the problem permanently?

**Comment by aaemnnosttv** [comment]
Yeah, that would work too, although more than necessary.

**Comment by khromov** [comment]
@aaemnnosttv Thank you for this lead, we will try it!

**Comment by aaemnnosttv** [comment]
Correction - no, because `composer install` will install exactly as it is defined within the lock file.

You can either

- Delete the `vendor` directory and the `composer.lock` file, then run `composer install`

OR

- Delete the `vendor` directory and run `composer update` to fix the lock file

OR

- Make the corrections to both the `vendor/composer/installed.json` and the `composer.lock` files. Then `composer install` will install the correct versions, and next time you run `composer update` the lock file urls will use the correct protocol.

**Comment by NoelLH** [comment]
I'm hoping the passing years of fixes and particularly what I understand about Composer 2's more self-consistent lock file construction will have resolved this now. Please reopen with more info if not.
