### ISSUE TITLE
"wpackagist-plugin/rest-api": "2.0-beta13.1" not showing up

### ISSUE THREAD

**Issue by greatislander** [outlandishideas/wpackagist#164]
The WordPress REST API feature plugin received a [security update](https://make.wordpress.org/core/2016/05/25/wp-rest-api-versions-2-0-beta-12-1-and-2-0-beta-13-1/) today. While the WordPress Packagist listing does show that it was updated this afternoon, the new version is not showing up, and the plugin doesn't get updated when using dev-trunk.

**Comment by jakejackson1** [comment]
A fix for this would be awesome!

**Comment by rlaan** [comment]
*bump* 
Love to see this issue fixed too.

**Comment by callamwilliams** [comment]
+1

**Comment by omnisite** [comment]
+1

**Comment by drumba** [comment]
+1

**Comment by tamlyn** [comment]
According to [the composer docs](https://getcomposer.org/doc/04-schema.md#version) `2.0-beta13.1` is not a valid version number. `2.0-beta13` is OK but the extra `.1` throws the version parser. 

WordPress Packagist could try and be clever and mutate invalid version identifiers into something Composer understands but at present it just ignores any releases with invalid versions (PRs welcome!).

The `dev-trunk` version always contains the latest `trunk` build from `svn` so that should be a suitable workaround in most cases.
