### ISSUE TITLE
preserved html editor markup plus

### ISSUE THREAD

**Issue by M4rTiNi** [outlandishideas/wpackagist#188]
Hello,

there is a bug in this:
if I have composer plugin:
```
"wpackagist-plugin/preserved-html-editor-markup-plus": "*"
```
I get an error
```
[RuntimeException]                                                                                                                   
  Package could not be downloaded, svn: E175002: Unable to connect to a repository at URL 'https://plugins.svn.wordpress.org/preserve  
  d-html-editor-markup-plus/tags/1.5.1'                                                                                                
  svn: E175002: OPTIONS of 'https://plugins.svn.wordpress.org/preserved-html-editor-markup-plus/tags/1.5.1': Server certificate verif  
  ication failed: issuer is not trusted (https://plugins.svn.wordpress.org)     
```

I think the problem is the url, if I look here: 
https://plugins.svn.wordpress.org/preserved-html-editor-markup-plus/tags/1.5.1 get 404 but if I search it manualy https://plugins.svn.wordpress.org/preserved-html-editor-markup-plus/tags/1.5.3%0d/ it is working.

any idea how to fix it?

**Comment by tamlyn** [comment]
I think this is caused by a bug in `wordpress.org`. If you look at the [Developers tab](https://wordpress.org/plugins/preserved-html-editor-markup-plus/developers/) of the plugin page you'll see that the links to the versions there are wrong too. It looks like `wordpress.org` incorrectly strips off any trailing spaces. We use the `wordpress.org` API to fetch available versions so we are affected by the same bug.

Possible solutions:
- [Submit a bug report](https://meta.trac.wordpress.org/)
- Ask the plugin author to remove the trailing space from their version names (almost certainly an error on their part)
- Use `dev-trunk` as the version specifier instead of `*` - this gets you the latest dev version regardless of versions and releases
