### ISSUE TITLE
Plugin all-in-one-seo-pack last version not available

### ISSUE THREAD

**Issue by aerogus** [outlandishideas/wpackagist#226]
In wpackagist.org, the last available version of WordPress plugin "all in one seo pack" is **2.3.12.2**

`"wpackagist-plugin/all-in-one-seo-pack": "2.3.12.2"`

But in https://wordpress.org/plugins/all-in-one-seo-pack/ the last version is **2.3.12.2.1** commited 6 days ago.

Is there any lag in wpackagist or another problem ?

**Comment by khromov** [comment]
@aerogus This is because `2.3.12.2.1` is not a valid version according to [Semantic versioning](http://semver.org/).

We use the  `composer/semver` package to resolve version info and the regexp only searches for a maximum of 4 cascading versions. (as per the standard) Related code: https://github.com/composer/semver/blob/0bdf393dbafaebf79a8517140f661cedf40e36a4/src/VersionParser.php#L129

WP doesn't technically use semantic versioning. Which is a shame. Changing the current implementation would take quite a bit of code and testing.

The fix for end users is to use `dev-trunk` for this plugin instead of specifying a version.

**Comment by aerogus** [comment]
Thanks @khromov for this detailed answer. I just contacted the plugin author (semperplugins.com) to notice him of this bug.

**Comment by michaeltorbert** [comment]
Thanks for letting us know. We'll make sure to keep it <5 in the future. 
For future reference, our github repo is https://github.com/semperfiwebdesign/all-in-one-seo-pack if you need to reference it or open an issue.
