### ISSUE TITLE
Bug with open-external-links-in-a-new-window

### ISSUE THREAD

**Issue by nickkeenan** [outlandishideas/wpackagist#261]
the v 1.3.2 package seems to be installing v 1.3.1 of the open-external-links-in-a-new-window plugin.

**Comment by khromov** [comment]
@nickkeenan Since we use data directly off WordPress.org, what likely happened is that the author forgot to increment the plugin version in his latest release. Please verify this by downloading the latest versions via WordPress.org and testing that, and leave an issue with the plugin author. 

If you have ruled out the above, you can create a new issue.
