### ISSUE TITLE
Only last or older versions available for wp-travel

### ISSUE THREAD

**Issue by alex-galey** [outlandishideas/wpackagist#296]
Only the last or older versions are available for wp-travel plugin
2.0.4 - 1.2.5 - 1.2.4

It seems new version is overriding the previous one everytime an upgrade is available

**Comment by khromov** [comment]
Hey @alex-galey 

It's because the author of the plugin has stopped adding tags and now only commits directly to `trunk/` folder. The last tag as 1.2.5. Thus, older versions aren't available. This is not a WPackagist issue, please open an issue on the plugin support forum.

http://plugins.svn.wordpress.org/wp-travel/tags/
