### ISSUE TITLE
WPackagist not using the latest plugin version

### ISSUE THREAD

**Issue by acf-extended** [outlandishideas/wpackagist#301]
Hello,

Just to let you know that WPackagist is not using the latest plugin version of ACF Extended.

WPackagist: https://wpackagist.org/search?q=acf-extended (version: 0.7.9.4)
WP Repository: https://wordpress.org/plugins/acf-extended/ (version: 0.7.9.9.9)

Do you know what's going on?

Thanks in advance!

**Comment by khromov** [comment]
Hey @acf-extended 

The version number `0.7.9.9.9` is not a valid version according to  [semantic versioning](https://semver.org/). We use Composers [VersionParser](https://github.com/outlandishideas/wpackagist/blob/master/src/Command/UpdateCommand.php#L12) class and it differs in implementation from the way WordPress.org parses versions, which is more lenient. However, I don't believe Composer supports anything but semantic versions, which is why we have this limitation.

I suggest you use the well-defined semver format, since it has well-defined definitions for what each version number means. (major / minor / patch). If you for example release 0.8.0, it will be picked up and available through WPackagist.

**Comment by acf-extended** [comment]
Hello,

Roger that, thanks for the explanations.

Regards.
