### ISSUE TITLE
Mailjet for WordPress

### ISSUE THREAD

**Issue by eartisan-uk** [outlandishideas/wpackagist#309]
It seems this plugin hasn't been properly 'packaged' (?) as it installs the entire repository. It's great if it can be fixed.

**Comment by ArnaudBan** [comment]
Same problème here. 
`Stable tag: 5.2.1` but that tag can't be found in your repository. It can be found on [wordpress.org](https://plugins.trac.wordpress.org/browser/mailjet-for-wordpress/tags)

**Comment by NoelLH** [comment]
@ArnaudBan version 5.2.1 is shown now. You can press the refresh icon to force an update for brand new tags.

This also doesn't sound like the same issue as the original message, though I'm not totally clear what that is @eartisan-uk. If you mean that Composer dependencies are part of the package, it sounds like that is just how plugins have to work because of WordPress's lack of native recursive dependency management.

**Comment by ArnaudBan** [comment]
@NoelLH Thank you for your response.

I think i have the same problème as @eartisan-uk . When a do a `composer require wpackagist-plugin/mailjet-for-wordpress` i get the entire SVN repositorie of the plugin, not only the correct version as expected.
![wpackagist-plugin:mailjet-for-wordpress](https://user-images.githubusercontent.com/1626370/82917757-1d034e00-9f74-11ea-9519-847c8ee5d6ee.png)
And in that "tags" folder there is no folder "5.2.1" and maybe that is the problème ?

**Comment by NoelLH** [comment]
@ArnaudBan thanks for following up. I can replicate the same. It looks like the 5.2.1 tag has been packaged wrong by the plugin author in the WordPress.org svn repo. Wpackagist is essentially a mirror so can't fix stuff like this.

If you download https://downloads.wordpress.org/plugin/mailjet-for-wordpress.5.2.1.zip you'll see that it is broken on Wp.org. This is the URI Wpackagist will build when the version 5.2.1 is specified.

The fix is to get the plugin author to fix the tag or a new one.

A workaround might be to request a `trunk` version so that something like https://downloads.wordpress.org/plugin/mailjet-for-wordpress.zip?timestamp=2020-05-28-12:00:00 is used instead. (I am new to the wpackagist code so this could represent a misunderstanding of how `trunk` works.) This is not the same as getting the 5.2.1 stable tag and while you should get any new 5.2.1 features you may well also get breaking, unreleased changes by relying on this even temporarily.

I'll close this as I don't think there is anything wpackagist can do to resolve this, but let me know if you disagree.
