### ISSUE TITLE
[Bug] cache-enabler 1.3.5 downloads 1.3.4

### ISSUE THREAD

**Issue by mahnunchik** [outlandishideas/wpackagist#310]
Hi, I've faced with the following behaviour:

Package: `"wpackagist-plugin/cache-enabler":"1.3.5"`

Produce:

```json
{
            "name": "wpackagist-plugin/cache-enabler",
            "version": "1.3.5",
            "source": {
                "type": "svn",
                "url": "https://plugins.svn.wordpress.org/cache-enabler/",
                "reference": "tags/1.3.5"
            },
            "dist": {
                "type": "zip",
                "url": "https://downloads.wordpress.org/plugin/cache-enabler.1.3.5.zip"
            },
            "require": {
                "composer/installers": "~1.0"
            },
            "type": "wordpress-plugin",
            "homepage": "https://wordpress.org/plugins/cache-enabler/"
        },
```

But there are version 1.3.4 in the archive https://downloads.wordpress.org/plugin/cache-enabler.1.3.5.zip

**Comment by johnbillion** [comment]
This is because the plugin author accidentally tagged 1.3.5 while the plugin header still said 1.3.4. It got fixed after the fact. You can see the log here: https://plugins.trac.wordpress.org/log/cache-enabler/

As a new version of the plugin hasn't been released, there's no way for wpackagist to be made aware fo this change.

**Comment by khromov** [comment]
Like @johnbillion says, Cache Enabler devs corrected the error after the fact so the zip on WordPress.org got updated, but because Composer typically caches the dist zip you might still be getting the older non-fixed zip. To fix this run `composer clear-cache` and then `composer install` and the new updated zip should be redownloaded from WPorg.

**Comment by mahnunchik** [comment]
Hi @johnbillion @khromov I'm using composer inside docker and on CI, so it isn't related to composer cache.

```bash
# /tmp/cache doesn't shared between runs
docker run --rm -it --volume $PWD:/app:delegated composer install
```
