### ISSUE TITLE
Database error on wpackagist site

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#327]
@NoelLH: After triggering an update for a plugin, the wpackagist site now shows an error message:
````
An exception occurred while executing 'UPDATE packages SET
last_fetched = datetime("now"), versions = :json, is_active = 1, display_name = :display_name
WHERE class_name = :class_name AND name = :name' with params ["ACF Quick Edit Fields", "Outlandish\\Wpackagist\\Package\\Plugin", "acf-quickedit-fields", "{\"3.0.0\":\"tags\\\/3.0.0\",\"3.0.1\":\"tags\\\/3.0.1\",\"3.0.2\":\"tags\\\/3.0.2\",\"3.0.3\":\"tags\\\/3.0.3\",\"3.0.4\":\"tags\\\/3.0.4\",\"3.0.5\":\"tags\\\/3.0.5\",\"3.0.6\":\"tags\\\/3.0.6\",\"3.0.7\":\"tags\\\/3.0.7\",\"3.0.8\":\"tags\\\/3.0.8\",\"3.1.0\":\"tags\\\/3.1.0\",\"3.1.1\":\"tags\\\/3.1.1\",\"dev-trunk\":\"trunk\"}"]:

SQLSTATE[HY000]: General error: 5 database is locked
````

**Comment by NoelLH** [comment]
Thanks @strarsis. I think we probably need to rethink where the DB lives too, but I'll add a re-try for this error mode in any case soon.

**Comment by khromov** [comment]
@NoelLH Please share if you find a solution! I think generally SQLite on EFS is a no-go because of locking issues. The database schema is not too complicated, so perhaps a migration to MySQL wouldn't be too bad? What do you think?

**Comment by NoelLH** [comment]
I think you're right that it's not suitable for the SQLite part in this case @khromov. I was semi-optimistic because I found a press release about EFS now working with SQLite from 2017, but that still doesn't mean it's a good fit, especially for multiple tasks / threads trying to do stuff in parallel. I think even if we can make it workable it will always be slooow.

I will add a `catch` for this case for now, but also see if I can quickly work up an alternative using a more scalable relational DB. My first pass will probably be PostgreSQL to keep options for text search indexes as open as possible, but I will try to get things into standard Doctrine models so it's a bit more DB vendor-agnostic too. Unfortunately we'll need to write models, replace the bespoke migrations stuff and change a few DB queries to get this working.

**Comment by NoelLH** [comment]
OK, I've given it a go – would be good to get eyes on this if anyone has a chance: https://github.com/outlandishideas/wpackagist/pull/329

**Comment by NoelLH** [comment]
This has live Postgres databases ready now and is en route to Production – staging is building slowly but looks like it's working. Unfortunately there will be a bit of time where we don't have all packages because the first build just takes a while, but I'm increasing the power for the CLI task to try and minimise this time.
