### ISSUE TITLE
Advanced Custom Fields Table Field plugin cannot be found

### ISSUE THREAD

**Issue by Bastiiaann24** [outlandishideas/wpackagist#381]
Hi,

I think there might be an issue with the Advanced Custom Fields Table Field plugin. Whenever we try to install or update it in our projects we get the following error:

` [Composer\Downloader\TransportException]
  The "https://wpackagist.org/p/wpackagist-plugin/advanced-custom-fields-table-fie
  ld%24151602dfd96c576769e853629d3b5242c00057b6270a079007b62ef2f3fc8def.json" file
   could not be downloaded (HTTP/2 404 )`

The entry in our composer.json is: `"wpackagist-plugin/advanced-custom-fields-table-field": "*"`

**Comment by jameelmoses** [comment]
Same issue here with the same plugin

**Comment by saulirajala** [comment]
Same here

**Comment by fschroiff** [comment]
same here!

**Comment by Pyxl-Jim** [comment]
Yep, same here.

**Comment by mrrrlou** [comment]
7 days later and it's still not working

**Comment by doit-jochem** [comment]
Same here

**Comment by NoelLH** [comment]
Hello! Please use reactions and not further messages for +1s so we can focus on new information.

Findings so far: Staging is working. Production is not regardless of `--no-cache` flag.

Production's last fetch/refresh was already earlier this morning (I triggered another) whereas Staging's is in Nov 2020. So the manual refresh mechanism, combined with the way provider groups are lumped together with behaviour that varies based on whether a timestamp is in the current year or not is probably involved.

UI for Staging now:
<img width="1021" alt="Screenshot 2021-02-03 at 10 47 31" src="https://user-images.githubusercontent.com/3274454/106736375-47320300-660d-11eb-9657-c02921b6deaa.png">

And Prod:
<img width="1041" alt="Screenshot 2021-02-03 at 10 47 35" src="https://user-images.githubusercontent.com/3274454/106736391-4c8f4d80-660d-11eb-8c5e-dd464a66da06.png">

**Comment by NoelLH** [comment]
My local managed to have this problem despite having its last update also in December 2020. But I think the lead re. date grouping changing over time is still relevant to the root cause.

Having established this was broken and finding the origin of the hash in `providers-2020-12` (**note:** the `%24` before hashes is an encoded `$` and not part of the hex 🤦 ), I tried removing the 3-monthly 2020 providers from the `root` package data, since they are now superseded by `2020`. This fixed the actual Composer operation on my local.

I'm not a huge fan of the grouping flipping immediately at the turn of the year, but we've come this far and I'm concerned that further changing this might now cause extra problems for users whose Composer clients have cached hashes based on this system.

So I think the next step is to systematically check `root` for old groupings as I just did manually, on each full update, and delete them.

**Comment by NoelLH** [comment]
The hopeful fix is rolling out to Staging. I'll test an update there and do a quick check for no wider regressions before rolling out to Production by this evening (UK)

**Comment by NoelLH** [comment]
Staging is deployed, has had an update run and looks promising. The package being loadable there still is not conclusive evidence of a fix as I think there's an element of chance as to whether impacted packages have their load attempted from the new or old format provider group when the year changes, but the root `packages.json` looks to have changed as expected and installs continue to work.

Rolling out to Production now.

**Comment by NoelLH** [comment]
Fix live – this should work going forward.
