### ISSUE TITLE
_tk theme generating an invalid config

### ISSUE THREAD

**Issue by ethanclevenger91** [outlandishideas/wpackagist#447]
```
$ composer require "wpackagist-theme/_tk":"1.1.10"
./composer.json has been updated

Installation failed, reverting ./composer.json and ./composer.lock to their original content.


  [RuntimeException]
  require.wpackagist-theme/_tk is invalid, it should have a vendor name, a forward slash, and a package name. The ven
  dor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+
  )*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$".
```

Maybe the underscore is throwing it for a loop? Unsure what's going on under the hood.

Ideally will get moved away from this unsupported theme anyway, but wanted to note in case it's an edge case that impacts other libraries.

**Comment by NoelLH** [comment]
Hey @ethanclevenger91 – you're right I think that the underscore is the problem. The error message comes direct from Composer and is pretty explicit: the overall name and part after the / must start with a letter or number.

I'm not really sure what we can do to resolve this cleanly given that we cannot reasonably expect to change how Composer itself works – do you have any ideas?

I think the 2 most plausible ways forward are:
* stop listing packages that don't meet these criteria so that at least it doesn't look like they are installable;
* somehow rename the slug in the package database – I am struggling to think of any safe way to do this without causing maintainability problems and the risk of a clash with other packages

**Comment by ethanclevenger91** [comment]
You've got it with potential clashes with other packages. As far as renaming goes, my ideas include:

- Remove slash (most potential for clash?)
- Prefix with something like `wpackagist`, resulting in `wpackagist-theme/wpackagist_tk` (least potential for clash?)

Obviously both problematic, but the third option is not listing such themes/plugins altogether. I wonder how many the issue impacts. Can't be many at all.

**Comment by ethanclevenger91** [comment]
Just did a quick CTRL+F through the [WordPress themes sitemap](https://wordpress.org/themes/sitemap-index-1.xml) and there aren't any that include underscores, let alone _leading_ underscores. The theme that prompted the issue wouldn't be included in this sitemap because WP doesn't list themes/plugins that haven't been updated for 2+ (or maybe 3+?) years for indexing.

So perhaps this is simply a wontfix. I've been pressing my client to swap it this particular theme anyway, given it's unmaintained.

**Comment by NoelLH** [comment]
Thanks for looking into the numbers @ethanclevenger91. I think I agree with you that this is unlikely to be prioritised by anybody for the foreseeable future, if we have no other use cases and yours is going away.

I'm going to close it for now, but please feel free to comment again if you or anybody thinks we should focus on this, or has another idea to handle this case without a lot of effort or side effects.
