### ISSUE TITLE
404 when the files change while composer is running.

### ISSUE THREAD

**Issue by lavoiesl** [outlandishideas/wpackagist#54]
This is not a critical bug, one can simply re-run composer to fix the problem, but it happened to me at least a dozen times.

This is what happens:
1. composer fetches `/packages.json`.
2. Wpackagist’s cronjob updates all the files.
3. composer, still running, tries to fetch `/p/providers-*` as mentioned in step 1, but the file was deleted, generating a 404.

Right now, this is the cronjob:
1. Building all `*.json` files to `/p.new/`.
2. Renaming `/p/` to `/p.old/`.
3. Renaming `/p.new/` to `/p/`.
4. Overwriting `/packages.json`.
5. Removing `/p.old/.`

I propose:
1. Listing all current `/p/*.json` files.
2. Building all `*.json` files in `/p/`.
   - Not replacing existing files (content haven’t changed).
   - Existing files are removed for the list in 1.
3. Overwriting `/packages.json`.
4. Remove the old files in the next cronjob (this is essentially step 0).

This also has the benefit of not changing the `Last-Modified` header.

I am willing to program it, I just wanted to discuss it first.

**Comment by tamlyn** [comment]
Sorry, I could swear I had already responded to this. Must have dreamt it. 

Yeah, something like this is a good idea. One problem I ran into is that deleting the files can be really slow. I think the file system is struggling with 36,000 files in one directory. Is it possible to change the `providers-url` to split the packages up by first letter, for example?

**Comment by lavoiesl** [comment]
No, `providers-url` cannot be changed, the problem is that we are using only 2 vendor prefixes. Maintaining a list instead of finding files each time should fix that problem though.

**Comment by minac** [comment]
Hi,
I'm facing the same problem here. Sometimes I get a 404 getting random package json files:
```The \"https://wpackagist.org/p/wpackagist-plugin/bugsnag%242252a1d5d9545dcd8ec081cf93ddef2bb35f15cf22f83384a46537294b1afb07.json\" file could not be downloaded (HTTP/1.1 404 Not Found)```

Running composer again it works, so it must be a race condition.

Is there a way to cache these things in composer.json so that the 404s happen less often or anything else on my side?

@lavoiesl did you manage to find a way around it?

Thanks!

**Comment by joaquimds** [comment]
Hi,

It's a fairly large piece of work to make the change suggested by @lavoiesl so we haven't yet been able to make this improvement. This is because the code that generates the files is fairly complex.

I'm honestly not sure when I'll have time to do this, so I welcome any PR that can help move us in the right direction.

Thanks,
Joaquim

**Comment by khromov** [comment]
Based on the idea by @lavoiesl , I wonder if this could be implemented like the following:

1. Listing all current `/p/*.json` files.
2. Building all `*.json` files in `/p/`.
   - Not replacing existing files (content haven’t changed).
3. Overwriting `/packages.json`.
4. Run a separate CRON job (every 2h) that:
    - Creates a list of current plugins based on the files `/p/provider-(.*).json
    - Deletes files that are no longer on this list **if** they are older than 60 minutes.

The only existing edge case for this would be if someone ran a Composer process for more than 60 minutes, which seems unlikely and acceptable.

The downside would be marginally increased space usage since old packages would stick around for 2-3 hours.

@lavoiesl @joaquimds - Thoughts?

**Comment by NoelLH** [comment]
I _think_ we fixed this as one of the side effects when moving package storage itself to `Outlandish\Wpackagist\Storage\Database` for deployed environments. Please comment or reopen if anyone thinks differently.
