### ISSUE TITLE
Missing package Contact form 7 to database extension

### ISSUE THREAD

**Issue by klipach** [outlandishideas/wpackagist#65]
Missing package https://wordpress.org/plugins/contact-form-7-to-database-extension/, it was on http://wpackagist.org, but disappeared several days ago

**Comment by lavoiesl** [comment]
@tamlyn I can’t replicate the problem on my local environment (it works), but PRs are still awaiting deployment, can you deploy and get back to me?

**Comment by klipach** [comment]
i try
`composer require wpackagist-plugin/contact-form-7-to-database-extension`

but get 

````
[InvalidArgumentException]
  Could not find package wpackagist-plugin/contact-form-7-to-database-extension at any version for your minimum-stability (stable). Check the package spell
  ing or your minimum-stability
```

only for this package

**Comment by lavoiesl** [comment]
@klipach Sorry for the misunderstanding, your problem is real, I am talking about my local installation of wpackagist, that is why I am asking @tamlyn to deploy the latest version before trying to find the real problem.

You can see on the search engine that your plugin exists but is marked as inactive: http://wpackagist.org/?q=contact-form-7-to-database-extension&type=plugin

**Comment by klipach** [comment]
Today everything works perfect

**Comment by lavoiesl** [comment]
This is all very odd.

**Comment by tamlyn** [comment]
Closing as this seems to be resolved. Feel free to reopen if it returns.
