### ISSUE TITLE
wp-valid-email not available

### ISSUE THREAD

**Issue by marshmallowcreme** [outlandishideas/wpackagist#69]
See the plugin here: 

https://wordpress.org/plugins/wp-valid-email/

It's not in your library.

**Comment by tamlyn** [comment]
It is in our database but it's inactive http://wpackagist.org/search?q=wp-valid-email

This is because the developer has only released one version labelled `.0.1` (notice the leading dot). This is tripping up Composer's version parser. You could ask the developer of the plugin to fix the version and republish. The change will appear on wpackagist.org within an hour.

@lavoiesl shouldn't plugins with no valid versions be getting at least a `dev-trunk` version?

**Comment by lavoiesl** [comment]
@tamlyn, we could try that, it seems it would be a decent quickfix for a lot of issues.

**Comment by NoelLH** [comment]
Appears to have been fixed in 2015
