### ISSUE TITLE
custom-login-url download path is wrong?

### ISSUE THREAD

**Issue by arlair** [outlandishideas/wpackagist#86]
Hi, I've been going along okay with other wpackagist packages and composer, but I had a problem installing custom-login-url found at:
https://wordpress.org/plugins/custom-login-url/

  - Installing wpackagist-plugin/custom-login-url (1.0.0)
    Downloading: connection...    Failed to download wpackagist-plugin/custom-login-url from dist: The "https://downloads.wordpress.org/plugin/custom-login-url.1.0.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found)

That URL does not exist, but if I try download 1.0.zip instead of 1.0.0.zip in a browser (I just took a stab in the dark) it actually works.
ie, https://downloads.wordpress.org/plugin/custom-login-url.1.0.zip

Version is 1.0.0 on the WordPress plugins page.
I have:
"wpackagist-plugin/custom-login-url": "~1.0",
in my composer.json

Thanks.

**Comment by tamlyn** [comment]
The problem is that the version in the plugin's [main file](http://plugins.svn.wordpress.org/custom-login-url/tags/1.0/custom-login-url.php) doesn't match the Subversion tag as referenced in the [readme.txt](http://plugins.svn.wordpress.org/custom-login-url/tags/1.0/readme.txt). You can also see this on the [plugin page](https://wordpress.org/plugins/custom-login-url/developers/) under **current version** where the link results in a 404.

My feeling is that this isn't something that wpackagist should be handling. We're just using the wordpress.org API to fetch the plugin versions. 

I'd suggest pointing out the version discrepancy to the plugin author. In the meantime, if you have `svn` installed locally `composer` will fall back to that when the direct download fails.
